### ISSUE TITLE
Question: Zen v2 or Zen v1

### ISSUE THREAD

**Issue by paoloantinori** [caksoylar/zmk-config#2]
Hi there!

Thank you very much for your excellent work! I've landed here while looking for a recent build of zmk that could be compatible with my Corneish Zen v2

I'm currently successfully using your config repo and everything is working just fine, but I have a question:

I've noticed that in you are referring to `v1` for the right sie. Is that on purpose, indifferent, or might it be a genuine typo?

https://github.com/caksoylar/zmk-config/blob/94e4c80b90bfedd474fbc77ba23bcd6cee2d915c/build.yaml#L20

**Comment by caksoylar** [comment]
Hi, I have a weird setup where I have a v1 (round 2 of the GB) right half and a v2 (round 3 of GB) left half. This is because the left half of my original v1 pair died and I was able to get a v2 replacement from Darryl.

By the way, feel free to use my config repo but note that I might occasionally rewrite the git history. In addition, [the ZMK branch](https://github.com/caksoylar/zmk/tree/caksoylar/zen-8bit) the `main` branch of this repo refers to is a personal experimental one, so things can occassionally go wrong. I document my "official" ZMK branches I maintain for others with Zen improvements in [this gist](https://gist.github.com/caksoylar/c411313990978e1903c244f03039187a), in case you haven't seen it. You could prefer to use one of those branches in your own config.

**Comment by paoloantinori** [comment]
oh, interesting! thanks for explaining that!

I'm currently using your `8-bit` zmk branch, mostly becasue I think it was the one closest to current upstream that included your patches.
But that was maybe my lazy way to get to something working quickly, I'm might decide to go down the path you are suggesting with more familiarity with the context (I've been playing with my second hand Corneish Zen for just a week)

**Comment by caksoylar** [comment]
FYI these are the details of the branches (that are partially explained in the gist):
- `caksoylar/zen-v1+v2`: This one tracks upstream `main` most closely; it only has the display improvement patches for Zen versions
- `caksoylar/zen-v1+v2+experimental`: This one is above branch, but also includes mouse keys support and a [behavior PR that I use frequently](https://github.com/zmkfirmware/zmk/pull/1366)
- `caksoylar/zen-8bit`: This one is my personal branch, which has some experimental features like the above one, some extra ones I am testing, and [the custom status screen I use on Zens](https://github.com/caksoylar/zmk-config/blob/main/config/zen-status-screen.md).

So if you want to stick closest to upstream you'd want `caksoylar/zen-v1+v2`. I just rebased all of them today so comparing them might be easier now.

**Comment by paoloantinori** [comment]
Great, thank you very much!
